name: telegram bot

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: send telegram message
        run: |
          curl -X POST "https://api.telegram.org/bot8569753840:AAGuept9mD3AG2IAP7TVH-R9Ctt4qHYuDYw/sendMessage" \
          -d chat_id=8664700798 \
          -d text=PRJ00_RUN
